name = "FormalizedSparse"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["FormalizedSparse"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0"

[[require]]
name = "TrustworthyKedlaya"
git = "https://github.com/YijunYuan/TrustworthyKedlaya.git"
rev = "6e935eb559147e8e9bda430a266d27b432087143"

[[lean_lib]]
name = "FormalizedSparse"
